# SPDX-License-Identifier: Apache-2.0
# reffs standalone NFSv4.2 server config for wardtest

[server]
port           = 2049
bind           = "*"
role           = "standalone"
minor_versions = [1, 2]
grace_period   = 5
workers        = 4

[backend]
type       = "ram"
path       = "/var/lib/reffs/data"
state_file = "/var/lib/reffs/mds"

[[export]]
path        = "/"
clients     = "*"
access      = "rw"
root_squash = false
flavors     = ["sys"]
